# Generated by Django 2.1 on 2018-08-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('chamber', models.CharField(default='', max_length=8)),
                ('session', models.CharField(default='', max_length=32)),
                ('session_id', models.CharField(default='', max_length=8)),
                ('title', models.CharField(default='', max_length=255)),
                ('passed_house', models.BooleanField(default=False)),
                ('passed_senate', models.BooleanField(default=False)),
                ('is_ratified', models.BooleanField(default=False)),
                ('is_law', models.BooleanField(default=False)),
            ],
        ),
    ]
